# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.global.parameters]
stack_name = "test"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_NAMED_IAM"
confirm_changeset = true
# resolve_s3 = true
stack_name = "flame"
region = "ap-northeast-1"
disable_rollback = true
image_repositories = []
resolve_s3 = true
s3_prefix = "flame"
parameter_overrides = "MyAccountId=\"050451366189\" MyLambdaCodeS3BucketName=\"flame-lambda-code-bucket\" MyLambdaCodeS3key=\"flame-lambda-code.zip\" MyLambdaFunctionName=\"FlameLambdaFunction\""

[default.package.parameters]
# resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
